name: febs action

on:
  push:
    branches: [ master ]
  #pull_request:
  # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1  #使用官方脚本创建java环境
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true

    - name: Deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./target/
        remote: /home/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}

    - name: Restart
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        # 重启的脚本，根据自身情况做相应改动，一般要做的是migrate数据库以及重启服务器
        script: |
          cp /home/febs.jar /projects/