# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: febs action

on:
  push:
    branches: [ master ]
  #pull_request:
  # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
      
    # Deploy
    - name: Deploy
      uses: actions/checkout@master
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        FOLDER: ./  # 要推送的文件夹，路径相对于代码仓库的根目录
        SERVER_DESTINATION: /home/  # 部署到目标文件夹