name: febs action

on:
  push:
    branches: [ master ]
  #pull_request:
  # branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1  #使用官方脚本创建java环境
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true
      
    # Deploy
    #- name: Deploy
    #  uses: actions/checkout@master
    #  env:
    #    host: ${{ secrets.HOST }}
    #    username: ${{ secrets.HOST_USER }}
    #    password: ${{ secrets.HOST_PASSWORD }}
    #    port: ${{ secrets.HOST_PORT }}
    #    FOLDER: ./  # 要推送的文件夹，路径相对于代码仓库的根目录
    #    SERVER_DESTINATION: /home/  # 部署到目标文件夹
    - name: scp
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./
        remote: /home/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}